spring.profiles.active=local

spring.datasource.url=jdbc:postgresql://ep-restless-sunset-a1bciox8-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Srh5YCX2wAfK

spring.flyway.url=jdbc:postgresql://ep-restless-sunset-a1bciox8-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.flyway.user=neondb_owner
spring.flyway.password=npg_Srh5YCX2wAfK
